defaultNamespace: koldun

helm:
  chart: .
  values: 
    image:
      tag: "" # {"$imagescan": "koldun:tag"}

imageScans:
  - policy:
      semver:
        range: "ci-*"
      alphabetical:
        order: asc
    image: "ghcr.io/gorizond/koldun"
    tagName: koldun
    interval: 10s
