apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: koldun
  namespace: kube-system
spec:
  chart: koldun
  repo: https://gorizond.github.io/koldun
  targetNamespace: koldun
  version: 0.1.6
  valuesContent: |
    image:
      tag: v0.1.6
    nats:
      enabled: true
    minio:
      enabled: true
      persistence:
        enabled: true
        size: 50Gi
    csi-s3:
      enabled: true
    operator:
      conversation:
        natsUrl: nats://koldun-nats:4222
        kvBucket: koldun_ttl
      extraArgs:
        - --backend-disable-think-filter=true
    ingressDefaults:
      dispatcherMetricsListen: ":9090"
