#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: hack/update-compose-coverage-baseline.sh [compose.coverprofile] [analytics/compose_coverage_baseline.json]

Reads the compose.coverprofile generated by `make compose-test`, extracts the
total coverage, and writes it to analytics/compose_coverage_baseline.json while
recording the current commit hash and timestamp.
EOF
}

if [[ "${1:-}" =~ ^(-h|--help)$ ]]; then
  usage
  exit 0
fi

COVERPROFILE=${1:-compose.coverprofile}
BASELINE=${2:-analytics/compose_coverage_baseline.json}

if [[ ! -f "$COVERPROFILE" ]]; then
  echo "cover profile \"$COVERPROFILE\" not found; run make compose-test first" >&2
  exit 1
fi

if ! command -v go >/dev/null 2>&1; then
  echo "go is required to parse the cover profile" >&2
  exit 1
fi

if ! command -v git >/dev/null 2>&1; then
  echo "git is required to record the commit hash" >&2
  exit 1
fi

coverage_output=$(go tool cover -func="$COVERPROFILE")
total_line=$(printf "%s\n" "$coverage_output" | grep -E 'total:')
if [[ -z "$total_line" ]]; then
  echo "failed to parse total coverage from $COVERPROFILE" >&2
  exit 1
fi

total_value=$(printf "%s\n" "$total_line" | awk '{print $3}' | tr -d '%')
commit_hash=$(git rev-parse HEAD)
short_commit=$(git rev-parse --short HEAD)
timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
summary=$(git show -s --format='%s' HEAD)

python3 - <<'PY' "$BASELINE" "$total_value" "$timestamp" "$commit_hash" "$short_commit" "$summary"
import json
import sys
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

baseline_path, total_value, timestamp, commit_hash, short_commit, summary = sys.argv[1:]
value = Decimal(total_value).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
payload = {
    "total": float(value),
    "updated_at": timestamp,
    "commit": commit_hash,
    "source": f"{short_commit} — {summary}",
}
path = Path(baseline_path)
path.parent.mkdir(parents=True, exist_ok=True)
path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
PY

printf "Baseline updated to %.2f%% (%s)\n" "$total_value" "$commit_hash"
