// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gorizond/koldun/pkg/natsutil (interfaces: NATSConn,NATSKeyValue)
//
// Generated by this command:
//
//	mockgen -destination=pkg/natsutil/mocks/mock_nats.go -package=mocks github.com/gorizond/koldun/pkg/natsutil NATSConn,NATSKeyValue
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	nats "github.com/nats-io/nats.go"
	gomock "go.uber.org/mock/gomock"
)

// MockNATSConn is a mock of NATSConn interface.
type MockNATSConn struct {
	ctrl     *gomock.Controller
	recorder *MockNATSConnMockRecorder
	isgomock struct{}
}

// MockNATSConnMockRecorder is the mock recorder for MockNATSConn.
type MockNATSConnMockRecorder struct {
	mock *MockNATSConn
}

// NewMockNATSConn creates a new mock instance.
func NewMockNATSConn(ctrl *gomock.Controller) *MockNATSConn {
	mock := &MockNATSConn{ctrl: ctrl}
	mock.recorder = &MockNATSConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNATSConn) EXPECT() *MockNATSConnMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockNATSConn) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockNATSConnMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockNATSConn)(nil).Close))
}

// Drain mocks base method.
func (m *MockNATSConn) Drain() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Drain")
	ret0, _ := ret[0].(error)
	return ret0
}

// Drain indicates an expected call of Drain.
func (mr *MockNATSConnMockRecorder) Drain() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Drain", reflect.TypeOf((*MockNATSConn)(nil).Drain))
}

// Flush mocks base method.
func (m *MockNATSConn) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockNATSConnMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockNATSConn)(nil).Flush))
}

// JetStream mocks base method.
func (m *MockNATSConn) JetStream(opts ...nats.JSOpt) (nats.JetStreamContext, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "JetStream", varargs...)
	ret0, _ := ret[0].(nats.JetStreamContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JetStream indicates an expected call of JetStream.
func (mr *MockNATSConnMockRecorder) JetStream(opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JetStream", reflect.TypeOf((*MockNATSConn)(nil).JetStream), opts...)
}

// Publish mocks base method.
func (m *MockNATSConn) Publish(subject string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", subject, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockNATSConnMockRecorder) Publish(subject, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockNATSConn)(nil).Publish), subject, data)
}

// QueueSubscribe mocks base method.
func (m *MockNATSConn) QueueSubscribe(subject, queue string, handler nats.MsgHandler) (*nats.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueSubscribe", subject, queue, handler)
	ret0, _ := ret[0].(*nats.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueueSubscribe indicates an expected call of QueueSubscribe.
func (mr *MockNATSConnMockRecorder) QueueSubscribe(subject, queue, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueSubscribe", reflect.TypeOf((*MockNATSConn)(nil).QueueSubscribe), subject, queue, handler)
}

// Subscribe mocks base method.
func (m *MockNATSConn) Subscribe(subject string, handler nats.MsgHandler) (*nats.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", subject, handler)
	ret0, _ := ret[0].(*nats.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockNATSConnMockRecorder) Subscribe(subject, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockNATSConn)(nil).Subscribe), subject, handler)
}

// SubscribeSync mocks base method.
func (m *MockNATSConn) SubscribeSync(subject string) (*nats.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeSync", subject)
	ret0, _ := ret[0].(*nats.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeSync indicates an expected call of SubscribeSync.
func (mr *MockNATSConnMockRecorder) SubscribeSync(subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeSync", reflect.TypeOf((*MockNATSConn)(nil).SubscribeSync), subject)
}

// MockNATSKeyValue is a mock of NATSKeyValue interface.
type MockNATSKeyValue struct {
	ctrl     *gomock.Controller
	recorder *MockNATSKeyValueMockRecorder
	isgomock struct{}
}

// MockNATSKeyValueMockRecorder is the mock recorder for MockNATSKeyValue.
type MockNATSKeyValueMockRecorder struct {
	mock *MockNATSKeyValue
}

// NewMockNATSKeyValue creates a new mock instance.
func NewMockNATSKeyValue(ctrl *gomock.Controller) *MockNATSKeyValue {
	mock := &MockNATSKeyValue{ctrl: ctrl}
	mock.recorder = &MockNATSKeyValueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNATSKeyValue) EXPECT() *MockNATSKeyValueMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNATSKeyValue) Create(key string, value []byte) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", key, value)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNATSKeyValueMockRecorder) Create(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNATSKeyValue)(nil).Create), key, value)
}

// Delete mocks base method.
func (m *MockNATSKeyValue) Delete(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNATSKeyValueMockRecorder) Delete(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNATSKeyValue)(nil).Delete), key)
}

// Get mocks base method.
func (m *MockNATSKeyValue) Get(key string) (nats.KeyValueEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(nats.KeyValueEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNATSKeyValueMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNATSKeyValue)(nil).Get), key)
}

// Keys mocks base method.
func (m *MockNATSKeyValue) Keys(opts ...nats.WatchOpt) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Keys", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Keys indicates an expected call of Keys.
func (mr *MockNATSKeyValueMockRecorder) Keys(opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Keys", reflect.TypeOf((*MockNATSKeyValue)(nil).Keys), opts...)
}

// Purge mocks base method.
func (m *MockNATSKeyValue) Purge(key string, opts ...nats.DeleteOpt) error {
	m.ctrl.T.Helper()
	varargs := []any{key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Purge", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Purge indicates an expected call of Purge.
func (mr *MockNATSKeyValueMockRecorder) Purge(key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Purge", reflect.TypeOf((*MockNATSKeyValue)(nil).Purge), varargs...)
}

// Put mocks base method.
func (m *MockNATSKeyValue) Put(key string, value []byte) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", key, value)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockNATSKeyValueMockRecorder) Put(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockNATSKeyValue)(nil).Put), key, value)
}

// Status mocks base method.
func (m *MockNATSKeyValue) Status() (nats.KeyValueStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(nats.KeyValueStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockNATSKeyValueMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockNATSKeyValue)(nil).Status))
}

// Update mocks base method.
func (m *MockNATSKeyValue) Update(key string, value []byte, revision uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", key, value, revision)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockNATSKeyValueMockRecorder) Update(key, value, revision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNATSKeyValue)(nil).Update), key, value, revision)
}

// Watch mocks base method.
func (m *MockNATSKeyValue) Watch(keys string, opts ...nats.WatchOpt) (nats.KeyWatcher, error) {
	m.ctrl.T.Helper()
	varargs := []any{keys}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Watch", varargs...)
	ret0, _ := ret[0].(nats.KeyWatcher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Watch indicates an expected call of Watch.
func (mr *MockNATSKeyValueMockRecorder) Watch(keys any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{keys}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockNATSKeyValue)(nil).Watch), varargs...)
}
