name: Build Distributed LLaMA Image

on:
  workflow_dispatch:
    inputs:
      refs:
        description: Comma or space separated list of refs (branches or tags) to build
        required: false
        default: main
  push:
    tags:
      - "dllama-*"

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.determine.outputs.matrix }}
    steps:
      - name: Determine refs to build
        id: determine
        run: |
          parse_refs() {
            local input="$1"
            if [ -z "$input" ]; then
              return 1
            fi
            echo "$input" | tr ',' '\n' | tr ' ' '\n' | awk 'NF'
          }

          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            refs=$(parse_refs "${{ github.event.inputs.refs }}") || true
          elif [[ "${GITHUB_REF}" == refs/tags/dllama-* ]]; then
            refs="${GITHUB_REF#refs/tags/}"
          else
            refs="main"
          fi

          if [ -z "$refs" ]; then
            refs="main"
          fi

          json=$(printf '%s\n' "$refs" | sort -u | jq -R . | jq -s '{ref: .}')
          echo "matrix=$json" >> "$GITHUB_OUTPUT"

  build:
    name: Build multi-arch image
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    env:
      BUILD_REF: ${{ matrix.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build distributed-llama Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/distributed-llama.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          build-args: |
            DL_VERSION=${{ env.BUILD_REF }}

      - name: Print success message
        run: |
          echo "Distributed-llama image build completed for ref: $BUILD_REF"
